---
title: "Module 4 - Instructions"
author: "Oliver Engist"
date: "04/04/2021"
output: pdf_document
---

In the next assignment we want to replicate some plots from the paper "Female Socialization: How Daughters Affect Their Legislator Fathers' Voting on Women's Issues" (Washington, 2008). The paper explores whether having a daughter makes politicians more sensitive to women's rights issues and how this is reflected in their voting behavior. The main identifying assumption is that after controlling for the number of children, the gender composition is random. This might be violated if families that have a preference for girls keep having children until they have a girl. In this assignment we will prepare a dataset that allows us to test whether families engage in such a "female child stopping rule".


# Setup

## Load the libraries "Rio" and "tidyverse"
## Change the path of the working directory to your working directory.

```{r, message=FALSE}

library(rio)
library(tidyverse)
library(magrittr)
library(knitr)
setwd("C:/Users/aless/Documents/Masterstudium SSE/Assignment 4 7613")
```

## Import the data sets basic.dta and genold108.dta
import("~/Masterstudium SSE/Assignment 4 7613/basic.dta")
import("~/Masterstudium SSE/Assignment 4 7613/genold108.dta")

## Create a subset of the 108th congress from the basic dataset
Congress108 <- basic %>% filter(congress=="108")

## Join this subset with the genold dataset
basic_genold_joined <- left_join(Congress108,genold108,by="name")

# Data preparation

## Check table 1 in the appendix of the paper and decide which variables are necessary for the analysis (check the footnote for control variables)

## From the control variables, I will drop the variable "service length" as well as its square since I think this has in the particular context of voting behavior regarding women's rights not a considerable influence as the other control variables which might clearly influence on the voting behavior as the other variables. Therefore, I consider it unnecessary.

## Drop all other variables
basic_genold_joined_clean <- basic_genold_joined %>% select(name,ngirls,anygirls,genold,totchi,party,rgroup,region,age,female,white)

## Recode genold such that gender is a factor variable and missing values are coded as NAs
basic_genold_joined_clean$genold <- as.factor(basic_genold_joined_clean$genold)

## Recode party as a factor with 3 levels (D, R, I)
basic_genold_joined_clean$party <- as.factor(basic_genold_joined_clean$party)
basic_genold_joined_clean$party <- recode(basic_genold_joined_clean$party,"1"="D","2"="R","3"="I")

## Recode rgroup and region as factors
basic_genold_joined_clean$rgroup <- as.factor(basic_genold_joined_clean$rgroup)

## Generate variables for age squared and service length squared
basic_genold_joined_clean %<>% mutate(age_2=age^2)

## Create an additional variable of the number of children as factor variable
basic_genold_joined_clean %<>% mutate(totchi_variable=totchi)
basic_genold_joined_clean$totchi_variable <- as.factor(basic_genold_joined_clean$totchi_variable)

# Replicationg Table 1 from the Appendix

### We haven't covered regressions in R yet. Use the function lm(). The function takes the regression model (formula) and the data as an input. The model is written as $y \sim x$, where $x$ stands for any linear combination of regressors (e.g. $y \sim x_1 + x_2 + female$). Use the help file to understand the function.

### Run the regression $total.children = \beta_0 + \beta_1 gender.oldest + \gamma'X$ where $\gamma$ stands for a vector of coefficients and $X$ is a matrix that contains all columns that are control variables.\footnote{This is just a short notation instead of writing the full model with all control variables $totchi = \beta_0 + \beta_1 genold + \gamma_1 age + \gamma_2 age^2 + \gamma_3 Democrat + ... + \epsilon$ which quickly gets out of hand for large models.}

### Save the main coefficient of interest ($\beta_1$)
### Run the same regression separately for Democrats and Republicans (assign the independent to one of the parties). Save the coefficient and standard error of genold

## Regression analysis (dependent variable:total children)
##Total Congress
lm.reg.congress.total <- lm(basic_genold_joined_clean$totchi ~ basic_genold_joined_clean$genold + basic_genold_joined_clean$region + basic_genold_joined_clean$rgroup + basic_genold_joined_clean$age + basic_genold_joined_clean$age_2 + basic_genold_joined_clean$female + basic_genold_joined_clean$white)
congress_total_totchi_beta <- summary(lm.reg.congress.total)$coefficients[2,1]
congress_total_totchi_sterr <- summary(lm.reg.congress.total)$coefficients[2,2]

## Democrats

## Filter democrats
data_democrats <- filter(basic_genold_joined_clean,party=="D")

## Regression analysis for democrats (dependent variable:total children)
lm.reg.congress.dem <- lm(data_democrats$totchi ~ data_democrats$genold + data_democrats$region + data_democrats$rgroup + data_democrats$age + data_democrats$age_2 + data_democrats$female + data_democrats$white)
democrats_totchi_beta <- summary(lm.reg.congress.dem)$coefficients[2,1]
democrats_totchi_sterr <- summary(lm.reg.congress.dem)$coefficients[2,2]

## Republicans

## Filter republicans
data_republicans <- filter(basic_genold_joined_clean,party=="R")

## Regression analysis for democrats (dependent variable:total children)
lm.reg.congress.rep <- lm(data_republicans$totchi ~ data_republicans$genold + data_republicans$region + data_republicans$rgroup + data_republicans$age + data_republicans$age_2 + data_republicans$female + data_republicans$white)
republicans_totchi_beta <- summary(lm.reg.congress.rep)$coefficients[2,1]
republicans_totchi_sterr <- summary(lm.reg.congress.rep)$coefficients[2,2]

## Regression analysis (dependent variable:number of girls)
##Total Congress
lm.reg.congress.total2 <- lm(basic_genold_joined_clean$ngirls ~ basic_genold_joined_clean$genold + basic_genold_joined_clean$region + basic_genold_joined_clean$rgroup + basic_genold_joined_clean$age + basic_genold_joined_clean$age_2 + basic_genold_joined_clean$female + basic_genold_joined_clean$white)
congress_total_ngirls_beta <- summary(lm.reg.congress.total2)$coefficients[2,1]
congress_total_ngirls_sterr <- summary(lm.reg.congress.total2)$coefficients[2,2]

## Democrats

## Regression analysis for democrats (dependent variable:number of girls)
lm.reg.congress.dem2 <- lm(data_democrats$ngirls ~ data_democrats$genold + data_democrats$region + data_democrats$rgroup + data_democrats$age + data_democrats$age_2 + data_democrats$female + data_democrats$white)
democrats_ngirls_beta <- summary(lm.reg.congress.dem2)$coefficients[2,1]
democrats_ngirls_sterr <- summary(lm.reg.congress.dem2)$coefficients[2,2]

## Republicans

## Regression analysis for democrats (dependent variable:number of girls)
lm.reg.congress.rep2 <- lm(data_republicans$ngirls ~ data_republicans$genold + data_republicans$region + data_republicans$rgroup + data_republicans$age + data_republicans$age_2 + data_republicans$female + data_republicans$white)
republicans_ngirls_beta <- summary(lm.reg.congress.rep2)$coefficients[2,1]
republicans_ngirls_sterr <- summary(lm.reg.congress.rep2)$coefficients[2,2]

## Collect all the genold coefficients from the six regressions, including their standard errors and arrange them in a table as in the paper.
summary_coefficients_totchi <- tibble(congress_total_totchi_beta,congress_total_totchi_sterr,democrats_totchi_beta,democrats_totchi_sterr,republicans_totchi_beta,republicans_totchi_sterr)

## Rename colums totchi
colnames(summary_coefficients_totchi)[1]<- "beta congress"
colnames(summary_coefficients_totchi)[2]<- "sterr congress"
colnames(summary_coefficients_totchi)[3]<- "beta democrats"
colnames(summary_coefficients_totchi)[4]<- "sterr democrats"
colnames(summary_coefficients_totchi)[5]<- "beta republicans"
colnames(summary_coefficients_totchi)[6]<- "sterr republicans"

summary_coefficients_ngirls <- tibble(congress_total_ngirls_beta,congress_total_ngirls_sterr,democrats_ngirls_beta,democrats_ngirls_sterr,republicans_ngirls_beta,republicans_ngirls_sterr)

## Rename colums ngirls
colnames(summary_coefficients_ngirls)[1]<- "beta congress"
colnames(summary_coefficients_ngirls)[2]<- "sterr congress"
colnames(summary_coefficients_ngirls)[3]<- "beta democrats"
colnames(summary_coefficients_ngirls)[4]<- "sterr democrats"
colnames(summary_coefficients_ngirls)[5]<- "beta republicans"
colnames(summary_coefficients_ngirls)[6]<- "sterr republicans"

table <- rbind(summary_coefficients_totchi,summary_coefficients_ngirls)

## Print the table
print(table)

```